steps:

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['use', 'socialape-d8699']

- name: 'gcr.io/cloud-builders/npm:node-10.10.0'
  dir: 'functions'
  args: ['install']

# Deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--only', 'functions']
  